[build]
  base = "my-app"                 # Navigate to the my-app directory first
  command = "CI=true npm run build"  # Correct CI variable usage
  publish = ".next"                # Correct Next.js output folder

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
