[build]
  command = CI='' npm run build
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"



# [build]
#   command = "CI= npm run build"

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
